name: Update Data

on: 
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'

permissions:
  contents: write  # crucial for private repos

jobs:
  update-geojson:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo content
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute Python script
        run: python script.py

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || git commit -m "[update] Update GeoJSON data"

      - name: Push changes (clearly fixed step)
        run: |
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git main
